---
language: ruby
services:
  - redis-server
cache: bundler
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
before_install:
  # Bundler 2.0 needs a newer RubyGems
  - gem update --system
  - gem install bundler
script: bundle exec rspec
