---
language: ruby
services:
  - redis-server
cache: bundler
matrix:
  # Bundler 2.0 does not support Ruby versions lower than 2.3
  include:
  - rvm: 2.1.10
    before_install: gem install bundler -v '< 2'
  - rvm: 2.2.10
    before_install: gem install bundler -v '< 2'
  - rvm: 2.3.7
    before_install: gem update --system; gem install bundler
  - rvm: 2.4.4
    before_install: gem update --system; gem install bundler
  - rvm: 2.5.1
    before_install: gem update --system; gem install bundler
script: bundle exec rspec
