---
language: ruby
services:
  - redis-server
cache: bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
before_install:
  # Bundler 2.0 needs a newer RubyGems
  - gem update --system
  - gem install bundler
script: bundle exec rspec
